CREATE TABLE [dbo].[Races]
(
  [Id] NVARCHAR(255) NOT NULL PRIMARY KEY,
  [PcsId] NVARCHAR(255) NULL,
  [StageId] NVARCHAR(64) NULL,
  [StageRaceId] NVARCHAR(255) NULL,
  [StageRace] BIT NOT NULL,
  [Name] NVARCHAR(MAX) NULL,
  [RaceDate] DATETIME NULL,
  [RaceType] NVARCHAR(20),
  [Distance] DECIMAL,
  [Elevation] INT NULL,
  [Duration] INT NULL,
  [Status] NVARCHAR(20),
  [ProfileImageUrl] NVARCHAR(128) NULL,
  [PointsScale] NVARCHAR(128) NULL,
  [UciScale] NVARCHAR(64) NULL,
  [ParcoursType] INT NULL,
  [ProfileScore] INT NULL,
  [RaceRanking] INT NULL,
  [StartlistQuality] INT NULL,
  [DecidingMethod] NVARCHAR(128) NULL,
  [Classification] NVARCHAR(128) NULL,
  [Category] NVARCHAR(128) NULL,
  [PcsUrl] NVARCHAR(255) NULL,
  [WcsUrl] NVARCHAR(255) NULL,
  [PointsRetrieved] BIT NOT NULL default( 0),
  [ResultsRetrieved] BIT NOT NULL default( 0),
  [StartListRetrieved] BIT NOT NULL default( 0),
  [DetailsCompleted] BIT NOT NULL default( 0),
  [GameOrganized] BIT NULL,
  [Error] NVARCHAR(MAX) NULL,
  [MarkForProcess] BIT NULL,
  [Updated] DATETIME2 NULL
)
