CREATE TABLE [dbo].[Races]
(
  [Id] NVARCHAR(255) NOT NULL PRIMARY KEY,
  [Name] NVARCHAR(MAX) NULL,
  RaceDate DATETIME NULL,
  [RaceType] NVARCHAR(20),
  [Distance] DECIMAL,
  Status NVARCHAR(20)
)
