CREATE TABLE [dbo].[Riders] (
    [Id]           NVARCHAR (255) NOT NULL,
    [PcsId]           NVARCHAR (255) NULL,
    [Name]         NVARCHAR (MAX) NOT NULL,
    [Team]         NVARCHAR (MAX) NOT NULL,
    [Status]           NVARCHAR (20) NOT NULL,
    DetailsCompleted    BIT NOT NULL,
    [BirthYear]    INT NOT NULL,
    [Weight]    INT NOT NULL,
    [Height]    INT NOT NULL,
    [RiderType]    INT NULL,
    [Ranking2019]  INT NULL,
    [Ranking2020]  INT NULL,
    [Ranking2021]  INT NULL,
    [Ranking2022]  INT NULL,
    [Ranking2023]  INT NULL,
    [Ranking2024]  INT NULL,
    [Ranking2025]  INT NULL,
    [Ranking2026]  INT NULL,
    Updated         DATETIME2 NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);
