name: wcs-scraper deployment

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'src/**'
    - '.github/workflows/ci-cd.yaml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_USERNAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.ACR_USERNAME }}.azurecr.io/wcs-scraper:${{ github.sha }} , ${{ secrets.ACR_USERNAME }}.azurecr.io/wcs-scraper:latest
          file: src/Dockerfile
          context: src/.


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy cycling database
        uses: azure/sql-action@v1.3
        with:        
          connection-string: '${{ secrets.SQL_CONNECTION }}'
          project-file: 'src/CyclingStats.Database/CyclingStats.Database.sqlproj'
          build-arguments: '-c Release'
          arguments: '/p:DropObjectsNotInSource=true' 

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n wcs-scraper -g cycling-stats --server ${{ secrets.ACR_USERNAME }}.azurecr.io --username  ${{ secrets.ACR_USERNAME }} --password ${{ secrets.ACR_PASSWORD }}
            az containerapp update -n wcs-scraper -g cycling-stats --image ${{ secrets.ACR_USERNAME }}.azurecr.io/wcs-scraper:${{ github.sha }} -v sql__connectionString=${{ secrets.SQL_CONNECTION }},wcs__baseUri="https://www.worldcyclingstats.com/en",